spring:
  thymeleaf:
    mode: HTML
    cache: true
    servlet:
      content-type: text/html
  messages:
    basename: i18n/messages
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: pro
comment.avatar: /images/avatar.jpg